### PR TITLE
Add EnvironmentDetector

### PR DESCRIPTION
**Pull request by JKamsker**
Detecting environments where colors are probably not supported.

### CODE REVIEW

**Comment by silkfire** [comment]
Looks really good! Great initiative 👌🏻

**Comment by JKamsker** [comment]
@silkfire Oh, glad you like it! I've added some tests :)

**Comment by silkfire** [comment]
Is there any reason you need to use the `lock` object when running the tests? I tried without and got not errors. The tests are not run in parallell so shouldn't cause any issues.

**Comment by JKamsker** [comment]
@silkfire I did not know if they run in parallel or not. I think there may be an option to do that. I added the lock just in case. 
Environment variables are global. I didnt want them to influence other tests.

**Comment by silkfire** [comment]
I used to run the unit tests in parallell but got unexpected results due to race conditions so I disabled the parallellization.

**Comment by silkfire** [comment]
I decided to go ahead and release this. Thanks for your work!

https://github.com/silkfire/Pastel/releases/tag/v4.2.0

**Comment by silkfire** [comment]
@JKamsker Better late than never, the new version of Pastel is out with considerably improved performance: [v5.0.0](https://github.com/silkfire/Pastel/releases/tag/v5.0.0)

**Pull request merged**
